##
# @author Guillaume Robin <>
# @file ESLint configuration
# @desc Created on 2019-10-23 9:14:53 pm
# @copyright GPL-3.0
#
parser: "babel-eslint"
extends: "airbnb"
plugins: ["react", "jsx-a11y", "import"]
rules:
  import/extensions: [0, "never"]

